spring:
  application:
    name: department-service

server:
  port: 9000

eureka:
  instance:
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 45
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

